---
title: "Considerações Finais"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Outliers, dados faltantes, viés de seleção, desatualizado, mudou ao longo do tempo



# Introdução

Ufa, muita coisa né? Sim, e aqui é só o começo


# Tópicos relacionados ao processo de modelagem

### de modo direto
- pé-processamento dos dados
- dados desbalanceados
- interpretabibilidade dos modelos 


### de modo indireto
- fairness / viés amostral / bias 
  - este tema é particularmente importante! Tem um documentário bacana chamado `Coded Bias` e aqui um artigo bem completo sobre o tema: [Algorithmic Fairness](https://arxiv.org/pdf/2001.09784.pdf)    
- Privacidade de dados e LGPD


# Outras técnicas/algoritmos/modelos

### Com um olhar mais próximo do universo da computação

- Deep Learning
- Reinforcement Learning
- Dados Não Estruturados
  - áudio
  - texto (processamento de linguagem natural)
  - imagem (visão computacional)
  

### Com um olhar mais próximo do universo da estatística

- Series Temporais
- Modelos bayesianos
- Análise de Sobrevivência
- métodos não paramêtricos


# Para entender melhor os fundamentos:

- Otimização
- Álgebra
- Amostragem
- Probabilidade 


# Referência

No fim do curso passaremos por algumas dicas mais gerais, mas aqui gostaria de deixar uma em particular: o canal no youtube do [Stat Quest](https://www.youtube.com/c/joshstarmer), do Josh Starmer. É simplesmente incrível, te ajuda a entender conceitos complexos de uma maneira muito acessível. Ah, ele mantem também um blog, como prefira: <https://statquest.org/>
